### ISSUE TITLE
Make it work on PHP 5.3

### ISSUE THREAD

**Issue by websoftix** [xiag-ag/rql-parser#2]
For those that want to use this great tool and cannot upgrade to PHP 5.4 (hopefully not many of us) I forked and adapted the code to work on PHP 5.3 here: https://github.com/websoftix/rql-parser/tree/worksOnPHP53.

**Comment by mrix** [comment]
I'm definitely will not support any unsupported [PHP versions](http://php.net/supported-versions.php).
Let's make PHP modern together.
