### ISSUE TITLE
Spaces in the string value

### ISSUE THREAD

**Issue by upnica** [xiag-ag/rql-parser#5]
I get the following error:

`Invalid character \" \" at position 14`

when executing the following query:

`(eq(field,some value with spaces))`

I have got around this by amending the REGEX_VALUE const in the Lexer class to:

`const REGEX_VALUE       = '/(\s|\w|\-|\+|\*|\?|\:|\.|\%[0-9a-f]{2})+/Ai';`

**Comment by mrix** [comment]
@upnica It isn't a [standard behavior](http://dundalek.com/rql/draft-zyp-rql-00.html). So I won't support this.
