### ISSUE TITLE
Doesn't work correct with LONG_INTEGER values

### ISSUE THREAD

**Issue by ittech227** [xiag-ag/rql-parser#6]
This code:
`$rql = 'eq(id,' . time() * 10 . ')';`
`$lexer = new Lexer();`
`$parser = Parser::createDefault();`
`$tokens = $lexer->tokenize($rql);`
`var_dump($tokens); `

will prints bellow:

class Xiag\Rql\Parser\Token#64 (3) {
      protected $value =>
      string(11) "14641796010"
      **protected $type =>
      int(1)**
      protected $position =>
      int(6)
    }

where $type == 1 is Xiag\Rql\Parser\Token::T_INTEGER.

Then Parser will do `(int) $value` and we'll get PHP_INT_MAX value instead my LONG_INT

**Comment by mrix** [comment]
Fixed in 82eb4155983775b6afec48a9c32f6bc8332161a6
