### ISSUE TITLE
rawurldecode for globs

### ISSUE THREAD

**Issue by dontub** [xiag-ag/rql-parser#7]
I think for globs rawurldecode should be used like for strings.
E.g. for `like(a,%5C*)` the glob should be `\*`.

**Comment by dontub** [comment]
I see now that it is done in `Glob::toRegex()`. As I need the glob string itself I'm currently using reflection (it should be possible without) to get it. However as mentioned in #1 I suggest to keep the glob as string.

**Comment by mrix** [comment]
Hi @dontub. This will break compatibility with the current implementation.
I'm going to fix it in 2.0.0.

**Comment by mrix** [comment]
Fixed in v2.0.0
