### ISSUE TITLE
Lexler error.

### ISSUE THREAD

**Issue by victorynox** [xiag-ag/rql-parser#9]
v1.0.2
The lexlet throw Exception `Invalid scalar token "select" (T_OPERATOR)` when I try to decode rgl string containing the name of the node rgl:
Example:
`eq(email,select%28a23sd%2Casd%2Casd%29)`
`eq(email,select(a23sd,asd,asd))`
And throw `Invalid scalar token "(" (T_OPEN_PARENTHESIS) ` when I try to decode rgl string with `(`

**Comment by derrekbertrand** [comment]
I think this is because it isn't designed to support nested selects. This could be added, but probably shouldn't be enabled by default, as now we're beginning to get into the realm of SQL.

**Comment by mrix** [comment]
Hi. Yes. That's true. You can't use operators inside `eq` (check [the documentation](https://github.com/persvr/rql#rql-rules)).
But if you really need it, please upgrade to v2 and implement your own `ValueParser`.

**Comment by derrekbertrand** [comment]
@bilal-renegade Please create a new issue if you need help. This one is closed.

You'll want to encode any special characters, including "(" and ")" when using RQL.

See the encoding docs:
https://github.com/libgraviton/rql-parser#encoding-rules
